### ISSUE TITLE
Test execution not finding executed tests 

### ISSUE THREAD

**Issue by blittle91** [jbadeau/xray-report#3]
A test has been executed and passed:
```
Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      1 executed      1 passed        0 failed        0 skipped
```
When the plugin attempts to upload the test execution results, it returns:

```
Uploading 1 test execution(s) to Jira Xray...
{
   "info":{
      "summary":"test-integration",
      "testEnvironments":[
         "UAT"
      ]
   },
   "tests":[
      
   ]
}
Failed to uploaded test execution to Jira Xray {"error":"Error assembling issue data: project is required"}
```

The spec file follows this format:

```
# Epic title

## Assert that 

tags: TCM-72

* When a step definition
___

* Tear down script
```

Where TCM-72 is the unique ID of an X-Ray test in Jira.

**Comment by jbadeau** [comment]
Are u using jira cloud? Currently this only works using the basic auth on the server edition. If you need cloud support then I could add it?

Please add the version of jira your using.

**Comment by blittle91** [comment]
No, not Jira cloud. We have Jira hosted on a server.

The Jira version is: 8.4.3.

That aside, ideally, I would like to use just the report generating functionality (rather than the automatic upload of tests).

If I pull in the relevant classes, it can't seem to find the `System.getenv("plugin_connection_port");`

Assuming this the Gauge API port, when it (successfully) connects to the socket, nothing is showing in the `socket.getInputStream()`.

**Comment by jbadeau** [comment]
Can you please run gauge -v and post the results ?

**Comment by jbadeau** [comment]
I will have a look this evening

**Comment by jbadeau** [comment]
Can you please run gauge -v and post the results ?

**Comment by jbadeau** [comment]
Just noticed that your tag is not correct

**Comment by jbadeau** [comment]
Is this still an issue?

**Comment by blittle91** [comment]
My apologies, I'm not using the framework anymore, so I'm unable to ascertain if this is still an issue.
