### ISSUE TITLE
is it possible to add authentication for jira cloud as well ?

### ISSUE THREAD

**Issue by tanneerumahesh** [jbadeau/xray-report#8]
Thanks for the plugin :) 
is it possible to add authentication for jira cloud as well?

**Comment by jbadeau** [comment]
yes, this can be added.
I will try to work on it next week

**Comment by jefdav** [comment]
Just wanted to follow up with request for the same as well. This would be a great automation for us, and we can only use it if Jira Cloud auth is supported.

**Comment by jbadeau** [comment]
Yes, I will add token based auth for Jira cloud this week

**Comment by jbadeau** [comment]
in progress

**Comment by jbadeau** [comment]
first versison will be basic auth then I will add ODIC after

**Comment by jbadeau** [comment]
Feel free to try out the latest beta release. I haven't tried it with Jira cloud yet as I don't have an instance but I will test next week.

**Comment by jbadeau** [comment]
any update?

**Comment by tanneerumahesh** [comment]
sorry just seen this! I am not using x-ray anymore so won't be able to test this.

**Comment by jbadeau** [comment]
added with v0.3.2
